### ISSUE TITLE
Allow common cross-environment configuration

### ISSUE THREAD

**Issue by janstenpickle** [shantytown/shanty#21]
Currently shanty only supports config per environment, but some plugins will require global configuration which exists across all environments. Propose something like this:

```yaml
---
- all:
  - docker:
    - nic: cage
- local
  - docker
    - nic: coppola
```
